# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
<!-- relative_permalinks: true -->

# Setup
title:            Fiona Torzewska

<!-- author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo -->

paginate:         3

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
